name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ v16.11.0 ]
    steps:
      - uses: actions/checkout@v4

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install package modules
        run: npm install
        working-directory: ./frontend

      - name: build project
        run: npm run build
        working-directory: ./frontend
